// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagement_SysDev;

#nullable disable

namespace SalesManagement_SysDev.Migrations
{
    [DbContext(typeof(SalesManagementContext))]
    partial class SalesManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesManagement_SysDev.LoginHistoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit")
                        .HasColumnName("IsSuccessful");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_LoginHistoryLog");

                    b.ToTable("LoginHistoryLog", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.MClient", b =>
                {
                    b.Property<int>("ClId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClId"));

                    b.Property<string>("ClAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClFax")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("ClFAX");

                    b.Property<int>("ClFlag")
                        .HasColumnType("int");

                    b.Property<string>("ClHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClPhone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ClPostal")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("SoId")
                        .HasColumnType("int")
                        .HasColumnName("SoID");

                    b.HasKey("ClId")
                        .HasName("PK__M_Client__B1FCF8D58C35E4D2");

                    b.HasIndex("SoId");

                    b.ToTable("M_Client", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.MEmployee", b =>
                {
                    b.Property<int>("EmId")
                        .HasColumnType("int")
                        .HasColumnName("EmID");

                    b.Property<int>("EmFlag")
                        .HasColumnType("int");

                    b.Property<string>("EmHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EmHiredate")
                        .HasColumnType("date");

                    b.Property<string>("EmName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmPassword")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EmPhone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("PoId")
                        .HasColumnType("int")
                        .HasColumnName("PoID");

                    b.Property<int>("SoId")
                        .HasColumnType("int")
                        .HasColumnName("SoID");

                    b.HasKey("EmId")
                        .HasName("PK__M_Employ__DCB5BEC24482B998");

                    b.HasIndex("PoId");

                    b.HasIndex("SoId");

                    b.ToTable("M_Employee", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.MMajorClassification", b =>
                {
                    b.Property<int>("McId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("McID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("McId"));

                    b.Property<int>("McFlag")
                        .HasColumnType("int");

                    b.Property<string>("McHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("McName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("McId")
                        .HasName("PK__M_MajorC__27B1E232B6CE2E6D");

                    b.ToTable("M_MajorClassification", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.MMaker", b =>
                {
                    b.Property<int>("MaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaId"));

                    b.Property<string>("MaAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaFax")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("MaFAX");

                    b.Property<int>("MaFlag")
                        .HasColumnType("int");

                    b.Property<string>("MaHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPhone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("MaPostal")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("MaId")
                        .HasName("PK__M_Maker__2725BF40FEBFC979");

                    b.ToTable("M_Maker", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.MPosition", b =>
                {
                    b.Property<int>("PoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoId"));

                    b.Property<int>("PoFlag")
                        .HasColumnType("int");

                    b.Property<string>("PoHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PoId")
                        .HasName("PK__M_Positi__A4C01F9E8A03A2CA");

                    b.ToTable("M_Position", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.MProduct", b =>
                {
                    b.Property<int>("PrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrId"));

                    b.Property<int>("MaId")
                        .HasColumnType("int")
                        .HasColumnName("MaID");

                    b.Property<string>("PrColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PrFlag")
                        .HasColumnType("int");

                    b.Property<string>("PrHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrJcode")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("PrJCode");

                    b.Property<string>("PrModelNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PrReleaseDate")
                        .HasColumnType("date");

                    b.Property<int>("PrSafetyStock")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9, 0)");

                    b.Property<int>("ScId")
                        .HasColumnType("int")
                        .HasColumnName("ScID");

                    b.HasKey("PrId")
                        .HasName("PK__M_Produc__A5021A4FEB48A98E");

                    b.HasIndex("MaId");

                    b.HasIndex("ScId");

                    b.ToTable("M_Product", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.MSalesOffice", b =>
                {
                    b.Property<int>("SoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoId"));

                    b.Property<string>("SoAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoFax")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)")
                        .HasColumnName("SoFAX");

                    b.Property<int>("SoFlag")
                        .HasColumnType("int");

                    b.Property<string>("SoHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoPhone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("SoPostal")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("SoId")
                        .HasName("PK__M_SalesO__BC3C9374243FA851");

                    b.ToTable("M_SalesOffice", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.MSmallClassification", b =>
                {
                    b.Property<int>("ScId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScId"));

                    b.Property<int>("McId")
                        .HasColumnType("int")
                        .HasColumnName("McID");

                    b.Property<int>("ScFlag")
                        .HasColumnType("int");

                    b.Property<string>("ScHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ScId")
                        .HasName("PK__M_SmallC__ACB791BA805D9A7F");

                    b.HasIndex("McId");

                    b.ToTable("M_SmallClassification", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TArrival", b =>
                {
                    b.Property<int>("ArId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ArID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArId"));

                    b.Property<DateTime?>("ArDate")
                        .HasColumnType("date");

                    b.Property<int>("ArFlag")
                        .HasColumnType("int");

                    b.Property<string>("ArHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ArStateFlag")
                        .HasColumnType("int");

                    b.Property<int>("ClId")
                        .HasColumnType("int")
                        .HasColumnName("ClID");

                    b.Property<int?>("EmId")
                        .HasColumnType("int")
                        .HasColumnName("EmID");

                    b.Property<int>("OrId")
                        .HasColumnType("int")
                        .HasColumnName("OrID");

                    b.Property<int>("SoId")
                        .HasColumnType("int")
                        .HasColumnName("SoID");

                    b.HasKey("ArId");

                    b.HasIndex("ClId");

                    b.HasIndex("EmId");

                    b.HasIndex("OrId");

                    b.HasIndex("SoId");

                    b.ToTable("T_Arrival", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TArrivalDetail", b =>
                {
                    b.Property<int>("ArDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ArDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArDetailId"));

                    b.Property<int?>("ArId")
                        .HasColumnType("int")
                        .HasColumnName("ArID");

                    b.Property<int?>("ArQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("PrId")
                        .HasColumnType("int")
                        .HasColumnName("PrID");

                    b.HasKey("ArDetailId");

                    b.HasIndex("ArId");

                    b.HasIndex("PrId");

                    b.ToTable("T_ArrivalDetail", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TChumon", b =>
                {
                    b.Property<int>("ChId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChId"));

                    b.Property<DateTime?>("ChDate")
                        .HasColumnType("date");

                    b.Property<int>("ChFlag")
                        .HasColumnType("int");

                    b.Property<string>("ChHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChStateFlag")
                        .HasColumnType("int");

                    b.Property<int>("ClId")
                        .HasColumnType("int")
                        .HasColumnName("ClID");

                    b.Property<int?>("EmId")
                        .HasColumnType("int")
                        .HasColumnName("EmID");

                    b.Property<int>("OrId")
                        .HasColumnType("int")
                        .HasColumnName("OrID");

                    b.Property<int>("SoId")
                        .HasColumnType("int")
                        .HasColumnName("SoID");

                    b.HasKey("ChId")
                        .HasName("PK__T_Chumon__AF02F0B8EDF28122");

                    b.HasIndex("ClId");

                    b.HasIndex("EmId");

                    b.HasIndex("OrId");

                    b.HasIndex("SoId");

                    b.ToTable("T_Chumon", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TChumonDetail", b =>
                {
                    b.Property<int>("ChDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChDetailId"));

                    b.Property<int>("ChId")
                        .HasColumnType("int")
                        .HasColumnName("ChID");

                    b.Property<int>("ChQuantity")
                        .HasColumnType("int");

                    b.Property<int>("PrId")
                        .HasColumnType("int")
                        .HasColumnName("PrID");

                    b.HasKey("ChDetailId");

                    b.HasIndex("ChId");

                    b.HasIndex("PrId");

                    b.ToTable("T_ChumonDetail", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.THattyu", b =>
                {
                    b.Property<int>("HaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HaId"));

                    b.Property<int>("EmId")
                        .HasColumnType("int")
                        .HasColumnName("EmID");

                    b.Property<DateTime>("HaDate")
                        .HasColumnType("date");

                    b.Property<int>("HaFlag")
                        .HasColumnType("int");

                    b.Property<string>("HaHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaId")
                        .HasColumnType("int")
                        .HasColumnName("MaID");

                    b.Property<int?>("WaWarehouseFlag")
                        .HasColumnType("int");

                    b.HasKey("HaId");

                    b.HasIndex("EmId");

                    b.HasIndex("MaId");

                    b.ToTable("T_Hattyu", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.THattyuDetail", b =>
                {
                    b.Property<int>("HaDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HaDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HaDetailId"));

                    b.Property<int>("HaId")
                        .HasColumnType("int")
                        .HasColumnName("HaID");

                    b.Property<int>("HaQuantity")
                        .HasColumnType("int");

                    b.Property<int>("PrId")
                        .HasColumnType("int")
                        .HasColumnName("PrID");

                    b.HasKey("HaDetailId");

                    b.HasIndex("HaId");

                    b.HasIndex("PrId");

                    b.ToTable("T_HattyuDetail", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TOrder", b =>
                {
                    b.Property<int>("OrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrId"));

                    b.Property<string>("ClCharge")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClId")
                        .HasColumnType("int")
                        .HasColumnName("ClID");

                    b.Property<int>("EmId")
                        .HasColumnType("int")
                        .HasColumnName("EmID");

                    b.Property<DateTime>("OrDate")
                        .HasColumnType("date");

                    b.Property<int>("OrFlag")
                        .HasColumnType("int");

                    b.Property<string>("OrHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrStateFlag")
                        .HasColumnType("int");

                    b.Property<int>("SoId")
                        .HasColumnType("int")
                        .HasColumnName("SoID");

                    b.HasKey("OrId")
                        .HasName("PK__T_Order__E1649648FAE4D6E9");

                    b.HasIndex("ClId");

                    b.HasIndex("EmId");

                    b.HasIndex("SoId");

                    b.ToTable("T_Order", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TOrderDetail", b =>
                {
                    b.Property<int>("OrDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrDetailId"));

                    b.Property<int>("OrId")
                        .HasColumnType("int")
                        .HasColumnName("OrID");

                    b.Property<int>("OrQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("OrTotalPrice")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<int>("PrId")
                        .HasColumnType("int")
                        .HasColumnName("PrID");

                    b.HasKey("OrDetailId")
                        .HasName("PK__T_OrderD__45EDE90EEC5B2390");

                    b.HasIndex("OrId");

                    b.HasIndex("PrId");

                    b.ToTable("T_OrderDetail", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TSale", b =>
                {
                    b.Property<int>("SaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaId"));

                    b.Property<int>("ClId")
                        .HasColumnType("int")
                        .HasColumnName("ClID");

                    b.Property<int>("EmId")
                        .HasColumnType("int")
                        .HasColumnName("EmID");

                    b.Property<int>("OrId")
                        .HasColumnType("int")
                        .HasColumnName("OrID");

                    b.Property<DateTime>("SaDate")
                        .HasColumnType("date");

                    b.Property<int>("SaFlag")
                        .HasColumnType("int");

                    b.Property<string>("SaHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoId")
                        .HasColumnType("int")
                        .HasColumnName("SoID");

                    b.HasKey("SaId");

                    b.HasIndex("ClId");

                    b.HasIndex("EmId");

                    b.HasIndex("OrId");

                    b.HasIndex("SoId");

                    b.ToTable("T_Sale", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TSaleDetail", b =>
                {
                    b.Property<int>("SaDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SaDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaDetailId"));

                    b.Property<int>("PrId")
                        .HasColumnType("int")
                        .HasColumnName("PrID");

                    b.Property<int>("SaId")
                        .HasColumnType("int")
                        .HasColumnName("SaID");

                    b.Property<decimal>("SaPrTotalPrice")
                        .HasColumnType("decimal(10, 0)");

                    b.Property<int>("SaQuantity")
                        .HasColumnType("int");

                    b.HasKey("SaDetailId");

                    b.HasIndex("PrId");

                    b.HasIndex("SaId");

                    b.ToTable("T_SaleDetail", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TShipment", b =>
                {
                    b.Property<int>("ShId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShId"));

                    b.Property<int>("ClId")
                        .HasColumnType("int")
                        .HasColumnName("ClID");

                    b.Property<int?>("EmId")
                        .HasColumnType("int")
                        .HasColumnName("EmID");

                    b.Property<int>("OrId")
                        .HasColumnType("int")
                        .HasColumnName("OrID");

                    b.Property<DateTime?>("ShFinishDate")
                        .HasColumnType("date");

                    b.Property<int>("ShFlag")
                        .HasColumnType("int");

                    b.Property<string>("ShHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShStateFlag")
                        .HasColumnType("int");

                    b.Property<int>("SoId")
                        .HasColumnType("int")
                        .HasColumnName("SoID");

                    b.HasKey("ShId");

                    b.HasIndex("ClId");

                    b.HasIndex("EmId");

                    b.HasIndex("OrId");

                    b.HasIndex("SoId");

                    b.ToTable("T_Shipment", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TShipmentDetail", b =>
                {
                    b.Property<int>("ShDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShDetailId"));

                    b.Property<int>("PrId")
                        .HasColumnType("int")
                        .HasColumnName("PrID");

                    b.Property<int>("ShId")
                        .HasColumnType("int")
                        .HasColumnName("ShID");

                    b.Property<int>("ShQuantity")
                        .HasColumnType("int");

                    b.HasKey("ShDetailId");

                    b.HasIndex("PrId");

                    b.HasIndex("ShId");

                    b.ToTable("T_ShipmentDetail", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TStock", b =>
                {
                    b.Property<int>("StId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StId"));

                    b.Property<int>("PrId")
                        .HasColumnType("int")
                        .HasColumnName("PrID");

                    b.Property<int>("StFlag")
                        .HasColumnType("int");

                    b.Property<int>("StQuantity")
                        .HasColumnType("int");

                    b.HasKey("StId")
                        .HasName("PK__T_Stock__C33CEFE204B2DFA6");

                    b.HasIndex("PrId");

                    b.ToTable("T_Stock", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TSyukko", b =>
                {
                    b.Property<int>("SyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SyId"));

                    b.Property<int>("ClId")
                        .HasColumnType("int")
                        .HasColumnName("ClID");

                    b.Property<int?>("EmId")
                        .HasColumnType("int")
                        .HasColumnName("EmID");

                    b.Property<int>("OrId")
                        .HasColumnType("int")
                        .HasColumnName("OrID");

                    b.Property<int>("SoId")
                        .HasColumnType("int")
                        .HasColumnName("SoID");

                    b.Property<DateTime?>("SyDate")
                        .HasColumnType("date");

                    b.Property<int>("SyFlag")
                        .HasColumnType("int");

                    b.Property<string>("SyHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SyStateFlag")
                        .HasColumnType("int");

                    b.HasKey("SyId");

                    b.HasIndex("ClId");

                    b.HasIndex("EmId");

                    b.HasIndex("OrId");

                    b.HasIndex("SoId");

                    b.ToTable("T_Syukko", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TSyukkoDetail", b =>
                {
                    b.Property<int>("SyDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SyDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SyDetailId"));

                    b.Property<int>("PrId")
                        .HasColumnType("int")
                        .HasColumnName("PrID");

                    b.Property<int>("SyId")
                        .HasColumnType("int")
                        .HasColumnName("SyID");

                    b.Property<int>("SyQuantity")
                        .HasColumnType("int");

                    b.HasKey("SyDetailId");

                    b.HasIndex("PrId");

                    b.HasIndex("SyId");

                    b.ToTable("T_SyukkoDetail", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TWarehousing", b =>
                {
                    b.Property<int>("WaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WaId"));

                    b.Property<int?>("EmId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EmID");

                    b.Property<int>("HaId")
                        .HasColumnType("int")
                        .HasColumnName("HaID");

                    b.Property<DateTime>("WaDate")
                        .HasColumnType("date");

                    b.Property<int>("WaFlag")
                        .HasColumnType("int");

                    b.Property<string>("WaHidden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WaShelfFlag")
                        .HasColumnType("int");

                    b.HasKey("WaId");

                    b.HasIndex("EmId");

                    b.HasIndex("HaId");

                    b.ToTable("T_Warehousing", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.TWarehousingDetail", b =>
                {
                    b.Property<int>("WaDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WaDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WaDetailId"));

                    b.Property<int>("PrId")
                        .HasColumnType("int")
                        .HasColumnName("PrID");

                    b.Property<int>("WaId")
                        .HasColumnType("int")
                        .HasColumnName("WaID");

                    b.Property<int>("WaQuantity")
                        .HasColumnType("int");

                    b.HasKey("WaDetailId");

                    b.HasIndex("PrId");

                    b.HasIndex("WaId");

                    b.ToTable("T_WarehousingDetail", (string)null);
                });

            modelBuilder.Entity("SalesManagement_SysDev.MClient", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MSalesOffice", "So")
                        .WithMany("MClients")
                        .HasForeignKey("SoId")
                        .IsRequired()
                        .HasConstraintName("FK_M_Client_ToM_SalesOffice");

                    b.Navigation("So");
                });

            modelBuilder.Entity("SalesManagement_SysDev.MEmployee", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MPosition", "Po")
                        .WithMany("MEmployees")
                        .HasForeignKey("PoId")
                        .IsRequired()
                        .HasConstraintName("FK_M_Employee_ToM_Position");

                    b.HasOne("SalesManagement_SysDev.MSalesOffice", "So")
                        .WithMany("MEmployees")
                        .HasForeignKey("SoId")
                        .IsRequired()
                        .HasConstraintName("FK_M_Employee_ToM_SalesOffice");

                    b.Navigation("Po");

                    b.Navigation("So");
                });

            modelBuilder.Entity("SalesManagement_SysDev.MProduct", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MMaker", "Ma")
                        .WithMany("MProducts")
                        .HasForeignKey("MaId")
                        .IsRequired()
                        .HasConstraintName("FK_M_Product_ToM_Maker");

                    b.HasOne("SalesManagement_SysDev.MSmallClassification", "Sc")
                        .WithMany("MProducts")
                        .HasForeignKey("ScId")
                        .IsRequired()
                        .HasConstraintName("FK_M_Product_ToM_SmallClassification");

                    b.Navigation("Ma");

                    b.Navigation("Sc");
                });

            modelBuilder.Entity("SalesManagement_SysDev.MSmallClassification", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MMajorClassification", "Mc")
                        .WithMany("MSmallClassifications")
                        .HasForeignKey("McId")
                        .IsRequired()
                        .HasConstraintName("FK_M_SmallClassification_ToM_MajorClassification");

                    b.Navigation("Mc");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TArrival", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MClient", "Cl")
                        .WithMany("TArrivals")
                        .HasForeignKey("ClId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Arrival_ToM_Client");

                    b.HasOne("SalesManagement_SysDev.MEmployee", "Em")
                        .WithMany("TArrivals")
                        .HasForeignKey("EmId")
                        .HasConstraintName("FK_T_Arrival_ToM_Employee");

                    b.HasOne("SalesManagement_SysDev.TOrder", "Or")
                        .WithMany("TArrivals")
                        .HasForeignKey("OrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Arrival_ToT_Order");

                    b.HasOne("SalesManagement_SysDev.MSalesOffice", "So")
                        .WithMany("TArrivals")
                        .HasForeignKey("SoId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Arrival_ToM_SalesOffice");

                    b.Navigation("Cl");

                    b.Navigation("Em");

                    b.Navigation("Or");

                    b.Navigation("So");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TArrivalDetail", b =>
                {
                    b.HasOne("SalesManagement_SysDev.TArrival", "Ar")
                        .WithMany("TArrivalDetails")
                        .HasForeignKey("ArId")
                        .HasConstraintName("FK_T_ArrivalDetail_ToT_Arrival");

                    b.HasOne("SalesManagement_SysDev.MProduct", "Pr")
                        .WithMany("TArrivalDetails")
                        .HasForeignKey("PrId")
                        .HasConstraintName("FK_T_ArrivalDetail_ToM_Product");

                    b.Navigation("Ar");

                    b.Navigation("Pr");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TChumon", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MClient", "Cl")
                        .WithMany("TChumons")
                        .HasForeignKey("ClId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Chumon_ToM_Client");

                    b.HasOne("SalesManagement_SysDev.MEmployee", "Em")
                        .WithMany("TChumons")
                        .HasForeignKey("EmId")
                        .HasConstraintName("FK_T_Chumon_ToM_Employee");

                    b.HasOne("SalesManagement_SysDev.TOrder", "Or")
                        .WithMany("TChumons")
                        .HasForeignKey("OrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Chumon_ToT_Order");

                    b.HasOne("SalesManagement_SysDev.MSalesOffice", "So")
                        .WithMany("TChumons")
                        .HasForeignKey("SoId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Chumon_ToM_SalesOffice");

                    b.Navigation("Cl");

                    b.Navigation("Em");

                    b.Navigation("Or");

                    b.Navigation("So");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TChumonDetail", b =>
                {
                    b.HasOne("SalesManagement_SysDev.TChumon", "Ch")
                        .WithMany("TChumonDetails")
                        .HasForeignKey("ChId")
                        .IsRequired()
                        .HasConstraintName("FK_T_ChumonDetail_ToT_Chumon");

                    b.HasOne("SalesManagement_SysDev.MProduct", "Pr")
                        .WithMany("TChumonDetails")
                        .HasForeignKey("PrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_ChumonDetail_ToM_Product");

                    b.Navigation("Ch");

                    b.Navigation("Pr");
                });

            modelBuilder.Entity("SalesManagement_SysDev.THattyu", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MEmployee", "Em")
                        .WithMany("THattyus")
                        .HasForeignKey("EmId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Hattyu_ToM_Employee");

                    b.HasOne("SalesManagement_SysDev.MMaker", "Ma")
                        .WithMany("THattyus")
                        .HasForeignKey("MaId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Hattyu_ToM_Maker");

                    b.Navigation("Em");

                    b.Navigation("Ma");
                });

            modelBuilder.Entity("SalesManagement_SysDev.THattyuDetail", b =>
                {
                    b.HasOne("SalesManagement_SysDev.THattyu", "Ha")
                        .WithMany("THattyuDetails")
                        .HasForeignKey("HaId")
                        .IsRequired()
                        .HasConstraintName("FK_T_HattyuDetail_ToT_Hattyu");

                    b.HasOne("SalesManagement_SysDev.MProduct", "Pr")
                        .WithMany("THattyuDetails")
                        .HasForeignKey("PrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_HattyuDetail_ToM_Product");

                    b.Navigation("Ha");

                    b.Navigation("Pr");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TOrder", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MClient", "Cl")
                        .WithMany("TOrders")
                        .HasForeignKey("ClId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Order_ToM_Client");

                    b.HasOne("SalesManagement_SysDev.MEmployee", "Em")
                        .WithMany("TOrders")
                        .HasForeignKey("EmId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Order_ToM_Employee");

                    b.HasOne("SalesManagement_SysDev.MSalesOffice", "So")
                        .WithMany("TOrders")
                        .HasForeignKey("SoId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Order_ToM_SalesOffice");

                    b.Navigation("Cl");

                    b.Navigation("Em");

                    b.Navigation("So");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TOrderDetail", b =>
                {
                    b.HasOne("SalesManagement_SysDev.TOrder", "Or")
                        .WithMany("TOrderDetails")
                        .HasForeignKey("OrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_OrderDetail_ToT_Order");

                    b.HasOne("SalesManagement_SysDev.MProduct", "Pr")
                        .WithMany("TOrderDetails")
                        .HasForeignKey("PrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_OrderDetail_ToM_Product");

                    b.Navigation("Or");

                    b.Navigation("Pr");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TSale", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MClient", "Cl")
                        .WithMany("TSales")
                        .HasForeignKey("ClId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Sale_ToM_Client");

                    b.HasOne("SalesManagement_SysDev.MEmployee", "Em")
                        .WithMany("TSales")
                        .HasForeignKey("EmId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Sale_ToM_Employee");

                    b.HasOne("SalesManagement_SysDev.TOrder", "Or")
                        .WithMany("TSales")
                        .HasForeignKey("OrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Sale_ToT_Order");

                    b.HasOne("SalesManagement_SysDev.MSalesOffice", "So")
                        .WithMany("TSales")
                        .HasForeignKey("SoId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Sale_ToM_SalesOffice");

                    b.Navigation("Cl");

                    b.Navigation("Em");

                    b.Navigation("Or");

                    b.Navigation("So");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TSaleDetail", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MProduct", "Pr")
                        .WithMany("TSaleDetails")
                        .HasForeignKey("PrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_SaleDetail_ToM_Product");

                    b.HasOne("SalesManagement_SysDev.TSale", "Sa")
                        .WithMany("TSaleDetails")
                        .HasForeignKey("SaId")
                        .IsRequired()
                        .HasConstraintName("FK_T_SaleDetail_ToT_Sale");

                    b.Navigation("Pr");

                    b.Navigation("Sa");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TShipment", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MClient", "Cl")
                        .WithMany("TShipments")
                        .HasForeignKey("ClId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Shipment_ToM_Client");

                    b.HasOne("SalesManagement_SysDev.MEmployee", "Em")
                        .WithMany("TShipments")
                        .HasForeignKey("EmId")
                        .HasConstraintName("FK_T_Shipment_ToM_Employee");

                    b.HasOne("SalesManagement_SysDev.TOrder", "Or")
                        .WithMany("TShipments")
                        .HasForeignKey("OrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Shipment_ToT_Order");

                    b.HasOne("SalesManagement_SysDev.MSalesOffice", "So")
                        .WithMany("TShipments")
                        .HasForeignKey("SoId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Shipment_ToM_SalesOffice");

                    b.Navigation("Cl");

                    b.Navigation("Em");

                    b.Navigation("Or");

                    b.Navigation("So");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TShipmentDetail", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MProduct", "Pr")
                        .WithMany("TShipmentDetails")
                        .HasForeignKey("PrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_ShipmentDetail_ToM_Product");

                    b.HasOne("SalesManagement_SysDev.TShipment", "Sh")
                        .WithMany("TShipmentDetails")
                        .HasForeignKey("ShId")
                        .IsRequired()
                        .HasConstraintName("FK_T_ShipmentDetail_ToT_Shipment");

                    b.Navigation("Pr");

                    b.Navigation("Sh");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TStock", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MProduct", "Pr")
                        .WithMany("TStocks")
                        .HasForeignKey("PrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Stock_ToM_Product");

                    b.Navigation("Pr");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TSyukko", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MClient", "Cl")
                        .WithMany("TSyukkos")
                        .HasForeignKey("ClId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Syukko_ToM_Client");

                    b.HasOne("SalesManagement_SysDev.MEmployee", "Em")
                        .WithMany("TSyukkos")
                        .HasForeignKey("EmId")
                        .HasConstraintName("FK_T_Syukko_ToM_Employee");

                    b.HasOne("SalesManagement_SysDev.TOrder", "Or")
                        .WithMany("TSyukkos")
                        .HasForeignKey("OrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Syukko_ToT_Order");

                    b.HasOne("SalesManagement_SysDev.MSalesOffice", "So")
                        .WithMany("TSyukkos")
                        .HasForeignKey("SoId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Syukko_ToM_SalesOffice");

                    b.Navigation("Cl");

                    b.Navigation("Em");

                    b.Navigation("Or");

                    b.Navigation("So");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TSyukkoDetail", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MProduct", "Pr")
                        .WithMany("TSyukkoDetails")
                        .HasForeignKey("PrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_SyukkoDetail_ToM_Product");

                    b.HasOne("SalesManagement_SysDev.TSyukko", "Sy")
                        .WithMany("TSyukkoDetails")
                        .HasForeignKey("SyId")
                        .IsRequired()
                        .HasConstraintName("FK_T_SyukkoDetail_ToT_Syukko");

                    b.Navigation("Pr");

                    b.Navigation("Sy");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TWarehousing", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MEmployee", "Em")
                        .WithMany("TWarehousings")
                        .HasForeignKey("EmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_T_Warehousing_ToM_Employee");

                    b.HasOne("SalesManagement_SysDev.THattyu", "Ha")
                        .WithMany("TWarehousings")
                        .HasForeignKey("HaId")
                        .IsRequired()
                        .HasConstraintName("FK_T_Warehousing_ToT_Hattyu");

                    b.Navigation("Em");

                    b.Navigation("Ha");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TWarehousingDetail", b =>
                {
                    b.HasOne("SalesManagement_SysDev.MProduct", "Pr")
                        .WithMany("TWarehousingDetails")
                        .HasForeignKey("PrId")
                        .IsRequired()
                        .HasConstraintName("FK_T_WarehousingDetail_ToM_Product");

                    b.HasOne("SalesManagement_SysDev.TWarehousing", "Wa")
                        .WithMany("TWarehousingDetails")
                        .HasForeignKey("WaId")
                        .IsRequired()
                        .HasConstraintName("FK_T_WarehousingDetail_ToT_Warehousing");

                    b.Navigation("Pr");

                    b.Navigation("Wa");
                });

            modelBuilder.Entity("SalesManagement_SysDev.MClient", b =>
                {
                    b.Navigation("TArrivals");

                    b.Navigation("TChumons");

                    b.Navigation("TOrders");

                    b.Navigation("TSales");

                    b.Navigation("TShipments");

                    b.Navigation("TSyukkos");
                });

            modelBuilder.Entity("SalesManagement_SysDev.MEmployee", b =>
                {
                    b.Navigation("TArrivals");

                    b.Navigation("TChumons");

                    b.Navigation("THattyus");

                    b.Navigation("TOrders");

                    b.Navigation("TSales");

                    b.Navigation("TShipments");

                    b.Navigation("TSyukkos");

                    b.Navigation("TWarehousings");
                });

            modelBuilder.Entity("SalesManagement_SysDev.MMajorClassification", b =>
                {
                    b.Navigation("MSmallClassifications");
                });

            modelBuilder.Entity("SalesManagement_SysDev.MMaker", b =>
                {
                    b.Navigation("MProducts");

                    b.Navigation("THattyus");
                });

            modelBuilder.Entity("SalesManagement_SysDev.MPosition", b =>
                {
                    b.Navigation("MEmployees");
                });

            modelBuilder.Entity("SalesManagement_SysDev.MProduct", b =>
                {
                    b.Navigation("TArrivalDetails");

                    b.Navigation("TChumonDetails");

                    b.Navigation("THattyuDetails");

                    b.Navigation("TOrderDetails");

                    b.Navigation("TSaleDetails");

                    b.Navigation("TShipmentDetails");

                    b.Navigation("TStocks");

                    b.Navigation("TSyukkoDetails");

                    b.Navigation("TWarehousingDetails");
                });

            modelBuilder.Entity("SalesManagement_SysDev.MSalesOffice", b =>
                {
                    b.Navigation("MClients");

                    b.Navigation("MEmployees");

                    b.Navigation("TArrivals");

                    b.Navigation("TChumons");

                    b.Navigation("TOrders");

                    b.Navigation("TSales");

                    b.Navigation("TShipments");

                    b.Navigation("TSyukkos");
                });

            modelBuilder.Entity("SalesManagement_SysDev.MSmallClassification", b =>
                {
                    b.Navigation("MProducts");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TArrival", b =>
                {
                    b.Navigation("TArrivalDetails");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TChumon", b =>
                {
                    b.Navigation("TChumonDetails");
                });

            modelBuilder.Entity("SalesManagement_SysDev.THattyu", b =>
                {
                    b.Navigation("THattyuDetails");

                    b.Navigation("TWarehousings");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TOrder", b =>
                {
                    b.Navigation("TArrivals");

                    b.Navigation("TChumons");

                    b.Navigation("TOrderDetails");

                    b.Navigation("TSales");

                    b.Navigation("TShipments");

                    b.Navigation("TSyukkos");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TSale", b =>
                {
                    b.Navigation("TSaleDetails");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TShipment", b =>
                {
                    b.Navigation("TShipmentDetails");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TSyukko", b =>
                {
                    b.Navigation("TSyukkoDetails");
                });

            modelBuilder.Entity("SalesManagement_SysDev.TWarehousing", b =>
                {
                    b.Navigation("TWarehousingDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
